version: "3.1"

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_groop
    environment:
      POSTGRES_USER: groop
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: groop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
